export const PRODUCT_GROUP_LIST_REQUEST = 'PRODUCT_GROUP_LIST_REQUEST';
export const PRODUCT_GROUP_LIST_SUCCESS = 'PRODUCT_GROUP_LIST_SUCCESS';
export const PRODUCT_GROUP_LIST_FAIL = 'PRODUCT_GROUP_LIST_FAIL';

export const PRODUCT_GROUP_DETAILS_REQUEST = 'PRODUCT_GROUP_DETAILS_REQUEST';
export const PRODUCT_GROUP_DETAILS_SUCCESS = 'PRODUCT_GROUP_DETAILS_SUCCESS';
export const PRODUCT_GROUP_DETAILS_FAIL = 'PRODUCT_GROUP_DETAILS_FAIL';

export const PRODUCT_GROUP_DELETE_REQUEST = 'PRODUCT_GROUP_DELETE_REQUEST';
export const PRODUCT_GROUP_DELETE_SUCCESS = 'PRODUCT_GROUP_DELETE_SUCCESS';
export const PRODUCT_GROUP_DELETE_FAIL = 'PRODUCT_GROUP_DELETE_FAIL';

export const PRODUCT_GROUP_CREATE_REQUEST = 'PRODUCT_GROUP_CREATE_REQUEST';
export const PRODUCT_GROUP_CREATE_SUCCESS = 'PRODUCT_GROUP_CREATE_SUCCESS';
export const PRODUCT_GROUP_CREATE_FAIL = 'PRODUCT_GROUP_CREATE_FAIL';
export const PRODUCT_GROUP_CREATE_RESET = 'PRODUCT_GROUP_CREATE_RESET';

export const PRODUCT_GROUP_UPDATE_REQUEST = 'PRODUCT_GROUP_UPDATE_REQUEST';
export const PRODUCT_GROUP_UPDATE_SUCCESS = 'PRODUCT_GROUP_UPDATE_SUCCESS';
export const PRODUCT_GROUP_UPDATE_FAIL = 'PRODUCT_GROUP_UPDATE_FAIL';
export const PRODUCT_GROUP_UPDATE_RESET = 'PRODUCT_GROUP_UPDATE_RESET';
