export const WISHLIST_ADD_ITEM = 'WISHLIST_ADD_ITEM';
export const WISHLIST_REMOVE_ITEM = 'WISHLIST_REMOVE_ITEM';
export const WISHLIST_LIST_REQUEST = 'WISHLIST_LIST_REQUEST';
export const WISHLIST_LIST_SUCCESS = 'WISHLIST_LIST_SUCCESS';
export const WISHLIST_LIST_FAIL = 'WISHLIST_LIST_FAIL';
export const WISHLIST_CLEAR = 'WISHLIST_CLEAR';

