export const seedUsers = [
  {
    name: 'Admin User',
    email: 'admin@example.com',
    password: 'admin123',
    isAdmin: true,
  },
  {
    name: 'John Doe',
    email: 'john@example.com',
    password: 'password123',
    isAdmin: false,
  },
  {
    name: 'Jane Smith',
    email: 'jane@example.com',
    password: 'password123',
    isAdmin: false,
  },
  {
    name: 'Michael Johnson',
    email: 'michael@example.com',
    password: 'password123',
    isAdmin: false,
  },
  {
    name: 'Emily Davis',
    email: 'emily@example.com',
    password: 'password123',
    isAdmin: false,
  },
  {
    name: 'David Wilson',
    email: 'david@example.com',
    password: 'password123',
    isAdmin: false,
  },
  {
    name: 'Sarah Brown',
    email: 'sarah@example.com',
    password: 'password123',
    isAdmin: false,
  },
  {
    name: 'Robert Taylor',
    email: 'robert@example.com',
    password: 'password123',
    isAdmin: false,
  },
  {
    name: 'Lisa Anderson',
    email: 'lisa@example.com',
    password: 'password123',
    isAdmin: false,
  },
  {
    name: 'James Martinez',
    email: 'james@example.com',
    password: 'password123',
    isAdmin: false,
  },
];

export const seedGroups = [
  {
    name: 'Advanced Mathematics',
    image: 'https://images.unsplash.com/photo-1509228468518-180dd4864904?w=500',
    code: 'MATH301',
    subject: 'Mathematics',
    medium: 'English',
    teacher: {
      name: 'Dr. Sarah Brown',
      title: 'Professor of Mathematics',
    },
    description: 'Advanced calculus and linear algebra course for undergraduate students.',
  },
  {
    name: 'Introduction to Physics',
    image: 'https://images.unsplash.com/photo-1636466497217-26a8cbeaf0aa?w=500',
    code: 'PHYS101',
    subject: 'Physics',
    medium: 'English',
    teacher: {
      name: 'Dr. Robert Taylor',
      title: 'Associate Professor of Physics',
    },
    description: 'Fundamental concepts in classical mechanics and thermodynamics.',
  },
  {
    name: 'English Literature',
    image: 'https://images.unsplash.com/photo-1457369804613-52c61a468e7d?w=500',
    code: 'ENG201',
    subject: 'English',
    medium: 'English',
    teacher: {
      name: 'Prof. Lisa Anderson',
      title: 'Senior Lecturer in English',
    },
    description: 'Exploring classic and modern English literature with critical analysis.',
  },
  {
    name: 'Computer Science Fundamentals',
    image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=500',
    code: 'CS101',
    subject: 'Computer Science',
    medium: 'English',
    teacher: {
      name: 'Dr. James Martinez',
      title: 'Assistant Professor of CS',
    },
    description: 'Introduction to programming, algorithms, and data structures.',
  },
  {
    name: 'Chemistry Basics',
    image: 'https://images.unsplash.com/photo-1603126857599-f6e157fa2fe6?w=500',
    code: 'CHEM101',
    subject: 'Chemistry',
    medium: 'English',
    teacher: {
      name: 'Dr. Emily Davis',
      title: 'Professor of Chemistry',
    },
    description: 'Basic principles of organic and inorganic chemistry.',
  },
  {
    name: 'World History',
    image: 'https://images.unsplash.com/photo-1461360370896-922624d12aa1?w=500',
    code: 'HIST202',
    subject: 'History',
    medium: 'English',
    teacher: {
      name: 'Dr. Michael Johnson',
      title: 'History Department Head',
    },
    description: 'Comprehensive study of world civilizations from ancient to modern times.',
  },
  {
    name: 'Biology and Life Sciences',
    image: 'https://images.unsplash.com/photo-1530973428-5bf2db2e4d71?w=500',
    code: 'BIO150',
    subject: 'Biology',
    medium: 'English',
    teacher: {
      name: 'Dr. David Wilson',
      title: 'Professor of Biology',
    },
    description: 'Introduction to cellular biology, genetics, and evolution.',
  },
  {
    name: 'Business Management',
    image: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=500',
    code: 'BUS301',
    subject: 'Business',
    medium: 'English',
    teacher: {
      name: 'Prof. Jane Smith',
      title: 'Business School Lecturer',
    },
    description: 'Strategic management, operations, and organizational behavior.',
  },
  {
    name: 'Art and Design',
    image: 'https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?w=500',
    code: 'ART101',
    subject: 'Arts',
    medium: 'English',
    teacher: {
      name: 'Ms. Sarah Brown',
      title: 'Art Instructor',
    },
    description: 'Fundamentals of visual arts, design principles, and creative expression.',
  },
  {
    name: 'Psychology 101',
    image: 'https://images.unsplash.com/photo-1507413245164-6160d8298b31?w=500',
    code: 'PSY101',
    subject: 'Psychology',
    medium: 'English',
    teacher: {
      name: 'Dr. John Doe',
      title: 'Clinical Psychologist',
    },
    description: 'Introduction to psychological theories, research methods, and applications.',
  },
];

export const seedProducts = [
  {
    name: 'Mathematics Grade 10 - Full Year Course',
    image: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=500',
    medium: 'English',
    category: 'Mathematics',
    grade: 10,
    subject: 'Mathematics',
    teacher: 'Dr. Sarah Brown',
    description:
      'Complete mathematics curriculum for grade 10 including algebra, geometry, and trigonometry. Interactive lessons with practice problems.',
    price: 12000,
    rating: 4.5,
    numReviews: 12,
    enrollmentCount: 245,
    isNewCourse: false,
    isBestseller: true,
    isPopular: true,
  },
  {
    name: 'Physics Grade 11 - Mechanics',
    image: 'https://images.unsplash.com/photo-1636466497217-26a8cbeaf0aa?w=500',
    medium: 'English',
    category: 'Science',
    grade: 11,
    subject: 'Physics',
    teacher: 'Dr. Robert Taylor',
    description:
      'Comprehensive physics course covering classical mechanics, forces, motion, and energy. Includes lab demonstrations.',
    price: 15000,
    rating: 4.8,
    numReviews: 8,
    enrollmentCount: 189,
    isNew: false,
    isBestseller: false,
    isPopular: true,
  },
  {
    name: 'English Literature - Poetry and Drama',
    image: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=500',
    medium: 'English',
    category: 'Language',
    grade: 9,
    subject: 'English',
    teacher: 'Prof. Lisa Anderson',
    description:
      'Explore classic and contemporary poetry and drama. Develop critical thinking and analysis skills.',
    price: 10000,
    rating: 4.3,
    numReviews: 15,
    enrollmentCount: 312,
    isNew: false,
    isBestseller: false,
    isPopular: true,
  },
  {
    name: 'Computer Science - Python Programming',
    image: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=500',
    medium: 'English',
    category: 'Technology',
    grade: 12,
    subject: 'Computer Science',
    teacher: 'Dr. James Martinez',
    description:
      'Learn Python programming from scratch. Covers data structures, algorithms, and real-world applications.',
    price: 18000,
    rating: 4.9,
    numReviews: 25,
    enrollmentCount: 428,
    isNew: false,
    isBestseller: true,
    isPopular: true,
  },
  {
    name: 'Chemistry Grade 10 - Organic Chemistry',
    image: 'https://images.unsplash.com/photo-1603126857599-f6e157fa2fe6?w=500',
    medium: 'English',
    category: 'Science',
    grade: 10,
    subject: 'Chemistry',
    teacher: 'Dr. Emily Davis',
    description:
      'Introduction to organic chemistry with focus on molecular structures, reactions, and laboratory techniques.',
    price: 13500,
    rating: 4.6,
    numReviews: 10,
    enrollmentCount: 167,
    isNewCourse: true,
    isBestseller: false,
    isPopular: false,
  },
  {
    name: 'World History - Ancient Civilizations',
    image: 'https://images.unsplash.com/photo-1461360370896-922624d12aa1?w=500',
    medium: 'English',
    category: 'Humanities',
    grade: 8,
    subject: 'History',
    teacher: 'Dr. Michael Johnson',
    description:
      'Journey through ancient civilizations including Egypt, Rome, Greece, and Mesopotamia.',
    price: 9500,
    rating: 4.4,
    numReviews: 18,
    enrollmentCount: 278,
    isNew: false,
    isBestseller: false,
    isPopular: true,
  },
  {
    name: 'Biology Grade 11 - Cell Biology',
    image: 'https://images.unsplash.com/photo-1576086213369-97a306d36557?w=500',
    medium: 'English',
    category: 'Science',
    grade: 11,
    subject: 'Biology',
    teacher: 'Dr. David Wilson',
    description:
      'In-depth study of cell structure, function, genetics, and molecular biology. Includes virtual lab simulations.',
    price: 14000,
    rating: 4.7,
    numReviews: 14,
    enrollmentCount: 203,
    isNew: false,
    isBestseller: true,
    isPopular: true,
  },
  {
    name: 'Business Studies - Entrepreneurship',
    image: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=500',
    medium: 'English',
    category: 'Business',
    grade: 12,
    subject: 'Business',
    teacher: 'Prof. Jane Smith',
    description:
      'Learn the fundamentals of starting and running a business. Covers business planning, marketing, and finance.',
    price: 16000,
    rating: 4.5,
    numReviews: 20,
    enrollmentCount: 156,
    isNew: true,
    isBestseller: false,
    isPopular: false,
  },
  {
    name: 'Art and Design - Digital Graphics',
    image: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=500',
    medium: 'English',
    category: 'Arts',
    grade: 10,
    subject: 'Arts',
    teacher: 'Ms. Sarah Brown',
    description:
      'Master digital art tools and techniques. Create stunning graphics, illustrations, and designs.',
    price: 11500,
    rating: 4.8,
    numReviews: 16,
    enrollmentCount: 234,
    isNew: false,
    isBestseller: false,
    isPopular: true,
  },
  {
    name: 'Psychology - Human Behavior',
    image: 'https://images.unsplash.com/photo-1507413245164-6160d8298b31?w=500',
    medium: 'English',
    category: 'Social Sciences',
    grade: 11,
    subject: 'Psychology',
    teacher: 'Dr. John Doe',
    description:
      'Understand human behavior, cognition, and mental processes. Explore psychological theories and research.',
    price: 12500,
    rating: 4.6,
    numReviews: 22,
    enrollmentCount: 191,
    isNew: true,
    isBestseller: false,
    isPopular: false,
  },
];

export const seedCarousel = [
  {
    name: 'Summer Learning Sale - Up to 30% Off',
    image: 'https://images.unsplash.com/photo-1607013251379-e6eecfffe234?w=1200',
    description: 'Get ready for the new semester with our biggest sale of the year. All courses discounted!',
  },
  {
    name: 'New Computer Science Courses Available',
    image: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=1200',
    description: 'Learn programming, web development, and data science from industry experts.',
  },
  {
    name: 'Mathematics Mastery Program',
    image: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=1200',
    description: 'Build strong mathematical foundations with our comprehensive curriculum.',
  },
  {
    name: 'Science Lab Simulations Now Available',
    image: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=1200',
    description: 'Experience virtual labs for Physics, Chemistry, and Biology experiments.',
  },
  {
    name: 'Enroll Now for Academic Year 2024',
    image: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=1200',
    description: 'Early bird registration is open. Secure your spot in popular courses today!',
  },
  {
    name: 'Excellence in English Literature',
    image: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=1200',
    description: 'Improve your language skills with our award-winning literature courses.',
  },
  {
    name: 'Business and Entrepreneurship Track',
    image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200',
    description: 'Prepare for the business world with practical skills and knowledge.',
  },
  {
    name: 'Creative Arts & Design Workshops',
    image: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=1200',
    description: 'Unleash your creativity with hands-on art and design courses.',
  },
  {
    name: 'Join Our Study Groups',
    image: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=1200',
    description: 'Connect with fellow students and learn together in collaborative groups.',
  },
  {
    name: 'Free Trial - Test Any Course',
    image: 'https://images.unsplash.com/photo-1488190211105-8b0e65b80b4e?w=1200',
    description: 'Try before you buy! Get free access to any course for 7 days.',
  },
];

export const seedCoupons = [
  {
    code: 'WELCOME10',
    discountType: 'percentage',
    discountValue: 10,
    description: 'Welcome offer! Get 10% off on your first purchase',
    expiryDate: new Date('2025-12-31'),
    minPurchaseAmount: 0,
    maxDiscountAmount: 1000,
    usageLimit: 1000,
    usedCount: 0,
    isActive: true,
  },
  {
    code: 'SAVE20',
    discountType: 'percentage',
    discountValue: 20,
    description: 'Save 20% on your purchase! Limited time offer',
    expiryDate: new Date('2025-12-31'),
    minPurchaseAmount: 2000,
    maxDiscountAmount: 2000,
    usageLimit: 500,
    usedCount: 0,
    isActive: true,
  },
  {
    code: 'FLASH50',
    discountType: 'fixed',
    discountValue: 50,
    description: 'Flash Sale! Get LKR 50 off',
    expiryDate: new Date('2025-12-31'),
    minPurchaseAmount: 500,
    usageLimit: 200,
    usedCount: 0,
    isActive: true,
  },
  {
    code: 'NEWYEAR25',
    discountType: 'percentage',
    discountValue: 25,
    description: 'New Year Special! 25% off on all courses',
    expiryDate: new Date('2026-01-31'),
    minPurchaseAmount: 1500,
    maxDiscountAmount: 3000,
    usedCount: 0,
    isActive: true,
  },
  {
    code: 'FREESHIP',
    discountType: 'fixed',
    discountValue: 100,
    description: 'Free shipping! LKR 100 off',
    expiryDate: new Date('2025-12-31'),
    minPurchaseAmount: 1000,
    usedCount: 0,
    isActive: true,
  },
];

